
language: objective-c
osx_image: xcode8.2

env:
  global:
    - WORKSPACE=Pageboy.xcworkspace
    - PROJECT=Sources/Pageboy.xcodeproj
    - SCHEME=Pageboy

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild -scheme $SCHEME -workspace $WORKSPACE -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' build test
- pod lib lint --quick

after_success:
  - bash <(curl -s https://codecov.io/bash)
