
language: objective-c
osx_image: xcode8.2

script:
  - xcodebuild -workspace Pageboy.xcworkspace -scheme Pageboy -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' build test
#  - pod lib lint --quick

after_success:
  - bash <(curl -s https://codecov.io/bash)
