language: objective-c
osx_image: xcode8.2
before_install:
- gem install bundler
- bundle install
script:
- bundle exec fastlane test
after_success:
- bundle exec fastlane deploy
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false